2023-09-17 10:37:13,516:INFO:PyCaret Supervised Module
2023-09-17 10:37:13,516:INFO:ML Usecase: classification
2023-09-17 10:37:13,517:INFO:version 2.3.3
2023-09-17 10:37:13,517:INFO:Initializing setup()
2023-09-17 10:37:13,517:INFO:setup(target=default, ml_usecase=classification, available_plots={'parameter': 'Hyperparameters', 'auc': 'AUC', 'confusion_matrix': 'Confusion Matrix', 'threshold': 'Threshold', 'pr': 'Precision Recall', 'error': 'Prediction Error', 'class_report': 'Class Report', 'rfe': 'Feature Selection', 'learning': 'Learning Curve', 'manifold': 'Manifold Learning', 'calibration': 'Calibration Curve', 'vc': 'Validation Curve', 'dimension': 'Dimensions', 'feature': 'Feature Importance', 'feature_all': 'Feature Importance (All)', 'boundary': 'Decision Boundary', 'lift': 'Lift Chart', 'gain': 'Gain Chart', 'tree': 'Decision Tree', 'ks': 'KS Statistic Plot'}, train_size=0.7, test_data=None, preprocess=True, imputation_type=simple, iterative_imputation_iters=5, categorical_features=None, categorical_imputation=constant, categorical_iterative_imputer=lightgbm, ordinal_features=None, high_cardinality_features=None, high_cardinality_method=frequency, numeric_features=None, numeric_imputation=mean, numeric_iterative_imputer=lightgbm, date_features=None, ignore_features=None, normalize=False, normalize_method=zscore, transformation=False, transformation_method=yeo-johnson, handle_unknown_categorical=True, unknown_categorical_method=least_frequent, pca=False, pca_method=linear, pca_components=None, ignore_low_variance=False, combine_rare_levels=False, rare_level_threshold=0.1, bin_numeric_features=None, remove_outliers=False, outliers_threshold=0.05, remove_multicollinearity=False, multicollinearity_threshold=0.9, remove_perfect_collinearity=True, create_clusters=False, cluster_iter=20, polynomial_features=False, polynomial_degree=2, trigonometry_features=False, polynomial_threshold=0.1, group_features=None, group_names=None, feature_selection=False, feature_selection_threshold=0.8, feature_selection_method=classic, feature_interaction=False, feature_ratio=False, interaction_threshold=0.01, fix_imbalance=False, fix_imbalance_method=None, transform_target=False, transform_target_method=box-cox, data_split_shuffle=True, data_split_stratify=False, fold_strategy=stratifiedkfold, fold=10, fold_shuffle=False, fold_groups=None, n_jobs=-1, use_gpu=False, custom_pipeline=None, html=True, session_id=123, log_experiment=False, experiment_name=None, log_plots=False, log_profile=False, log_data=False, silent=False, verbose=True, profile=False, profile_kwargs=None, display=None)
2023-09-17 10:37:13,517:INFO:Checking environment
2023-09-17 10:37:13,517:INFO:python_version: 3.7.6
2023-09-17 10:37:13,517:INFO:python_build: ('default', 'Jan  8 2020 19:59:22')
2023-09-17 10:37:13,517:INFO:machine: x86_64
2023-09-17 10:37:13,518:INFO:platform: Linux-5.4.0-1103-aws-x86_64-with-debian-buster-sid
2023-09-17 10:37:13,518:INFO:Memory: svmem(total=67415244800, available=56713977856, percent=15.9, used=9958789120, free=31841214464, active=20595306496, inactive=12024295424, buffers=1892081664, cached=23723159552, shared=1130496, slab=2606911488)
2023-09-17 10:37:13,520:INFO:Physical Core: 8
2023-09-17 10:37:13,520:INFO:Logical Core: 16
2023-09-17 10:37:13,520:INFO:Checking libraries
2023-09-17 10:37:13,520:INFO:pd==1.3.5
2023-09-17 10:37:13,520:INFO:numpy==1.21.6
2023-09-17 10:37:13,520:INFO:sklearn==0.23.2
2023-09-17 10:37:13,520:INFO:lightgbm==3.2.1
2023-09-17 10:37:13,521:WARNING:catboost not found
2023-09-17 10:37:13,542:INFO:xgboost==1.6.1
2023-09-17 10:37:14,315:INFO:mlflow==1.20.1
2023-09-17 10:37:14,315:INFO:Checking Exceptions
2023-09-17 10:37:14,315:INFO:Declaring global variables
2023-09-17 10:37:14,315:INFO:USI: 00ec
2023-09-17 10:37:14,315:INFO:pycaret_globals: {'fold_groups_param_full', 'stratify_param', '_ml_usecase', 'USI', '_gpu_n_jobs_param', 'n_jobs_param', 'create_model_container', 'imputation_regressor', '_all_metrics', '_available_plots', '_internal_pipeline', 'fold_groups_param', 'exp_name_log', 'data_before_preprocess', 'log_plots_param', 'seed', 'X_test', '_all_models', '_all_models_internal', 'html_param', 'fold_param', 'transform_target_param', 'iterative_imputation_iters_param', 'X', 'pycaret_globals', 'experiment__', 'master_model_container', 'gpu_param', 'target_param', 'logging_param', 'y_train', 'fold_shuffle_param', 'fix_imbalance_param', 'display_container', 'imputation_classifier', 'fold_generator', 'y_test', 'y', 'prep_pipe', 'X_train', 'transform_target_method_param', 'fix_imbalance_method_param'}
2023-09-17 10:37:14,315:INFO:Preparing display monitor
2023-09-17 10:37:14,316:INFO:Preparing display monitor
2023-09-17 10:37:14,330:INFO:Importing libraries
2023-09-17 10:37:14,330:INFO:Copying data for preprocessing
2023-09-17 10:37:14,418:INFO:Declaring preprocessing parameters
2023-09-17 10:37:14,569:INFO:Creating preprocessing pipeline
2023-09-17 10:37:16,645:INFO:Preprocessing pipeline created successfully
2023-09-17 10:37:16,645:ERROR:(Process Exit): setup has been interupted with user command 'quit'. setup must rerun.
2023-09-17 10:37:16,646:INFO:Creating global containers
2023-09-17 10:37:16,648:INFO:Internal pipeline: Pipeline(memory=None, steps=[('empty_step', 'passthrough')], verbose=False)
2023-09-17 10:38:11,655:WARNING:Couldn't import catboost.CatBoostClassifier
2023-09-17 10:38:11,742:WARNING:Couldn't import catboost.CatBoostClassifier
2023-09-17 10:38:11,742:INFO:Creating grid variables
2023-09-17 10:38:11,994:INFO:create_model_container: 0
2023-09-17 10:38:11,994:INFO:master_model_container: 0
2023-09-17 10:38:11,994:INFO:display_container: 1
2023-09-17 10:38:12,000:INFO:Pipeline(memory=None,
         steps=[('dtypes',
                 DataTypes_Auto_infer(categorical_features=[],
                                      display_types=True, features_todrop=[],
                                      id_columns=[],
                                      ml_usecase='classification',
                                      numerical_features=[], target='default',
                                      time_features=[])),
                ('imputer',
                 Simple_Imputer(categorical_strategy='not_available',
                                fill_value_categorical=None,
                                fill_value_numerical=None,
                                numeric_stra...
                ('scaling', 'passthrough'), ('P_transform', 'passthrough'),
                ('binn', 'passthrough'), ('rem_outliers', 'passthrough'),
                ('cluster_all', 'passthrough'),
                ('dummy', Dummify(target='default')),
                ('fix_perfect', Remove_100(target='default')),
                ('clean_names', Clean_Colum_Names()),
                ('feature_select', 'passthrough'), ('fix_multi', 'passthrough'),
                ('dfs', 'passthrough'), ('pca', 'passthrough')],
         verbose=False)
2023-09-17 10:38:12,000:INFO:setup() succesfully completed......................................
2023-09-17 10:38:12,107:INFO:Initializing compare_models()
2023-09-17 10:38:12,107:INFO:compare_models(include=None, fold=None, round=4, cross_validation=True, sort=Accuracy, n_select=1, budget_time=None, turbo=True, errors=ignore, fit_kwargs=None, groups=None, verbose=True, display=None, exclude=None)
2023-09-17 10:38:12,107:INFO:Checking exceptions
2023-09-17 10:38:12,115:INFO:Preparing display monitor
2023-09-17 10:38:12,115:INFO:Preparing display monitor
2023-09-17 10:38:12,145:INFO:Initializing Logistic Regression
2023-09-17 10:38:12,145:INFO:Total runtime is 2.853075663248698e-06 minutes
2023-09-17 10:38:12,154:INFO:SubProcess create_model() called ==================================
2023-09-17 10:38:12,155:INFO:Initializing create_model()
2023-09-17 10:38:12,155:INFO:create_model(estimator=lr, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7fb0c4031690>, kwargs={})
2023-09-17 10:38:12,155:INFO:Checking exceptions
2023-09-17 10:38:12,155:INFO:Importing libraries
2023-09-17 10:38:12,155:INFO:Copying training dataset
2023-09-17 10:38:12,207:INFO:Defining folds
2023-09-17 10:38:12,207:INFO:Declaring metric variables
2023-09-17 10:38:12,217:INFO:Importing untrained model
2023-09-17 10:38:12,226:INFO:Logistic Regression Imported succesfully
2023-09-17 10:38:12,244:INFO:Starting cross validation
2023-09-17 10:38:12,245:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-09-17 10:39:32,127:INFO:Calculating mean and std
2023-09-17 10:39:32,129:INFO:Creating metrics dataframe
2023-09-17 10:39:32,136:INFO:Uploading results into container
2023-09-17 10:39:32,136:INFO:Uploading model into container now
2023-09-17 10:39:32,136:INFO:create_model_container: 1
2023-09-17 10:39:32,136:INFO:master_model_container: 1
2023-09-17 10:39:32,136:INFO:display_container: 2
2023-09-17 10:39:32,137:INFO:LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=123, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)
2023-09-17 10:39:32,137:INFO:create_model() succesfully completed......................................
2023-09-17 10:39:32,245:INFO:SubProcess create_model() end ==================================
2023-09-17 10:39:32,245:INFO:Creating metrics dataframe
2023-09-17 10:39:32,264:INFO:Initializing K Neighbors Classifier
2023-09-17 10:39:32,264:INFO:Total runtime is 1.335325797398885 minutes
2023-09-17 10:39:32,274:INFO:SubProcess create_model() called ==================================
2023-09-17 10:39:32,274:INFO:Initializing create_model()
2023-09-17 10:39:32,275:INFO:create_model(estimator=knn, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7fb0c4031690>, kwargs={})
2023-09-17 10:39:32,275:INFO:Checking exceptions
2023-09-17 10:39:32,275:INFO:Importing libraries
2023-09-17 10:39:32,275:INFO:Copying training dataset
2023-09-17 10:39:32,327:INFO:Defining folds
2023-09-17 10:39:32,327:INFO:Declaring metric variables
2023-09-17 10:39:32,336:INFO:Importing untrained model
2023-09-17 10:39:32,345:INFO:K Neighbors Classifier Imported succesfully
2023-09-17 10:39:32,363:INFO:Starting cross validation
2023-09-17 10:39:32,364:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-09-17 11:04:17,939:WARNING:create_model() for knn raised an exception or returned all 0.0, trying without fit_kwargs:
2023-09-17 11:04:17,946:WARNING:Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pycaret/internal/tabular.py", line 2176, in compare_models
    refit=False,
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pycaret/internal/tabular.py", line 3125, in create_model_supervised
    error_score=0,
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py", line 248, in cross_validate
    for train, test in cv.split(X, y, groups))
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 1017, in __call__
    self.retrieve()
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 909, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 562, in wrap_future_result
    return future.result(timeout=timeout)
  File "/home/ubuntu/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 430, in result
    self._condition.wait(timeout)
  File "/home/ubuntu/anaconda3/lib/python3.7/threading.py", line 296, in wait
    waiter.acquire()
KeyboardInterrupt

2023-09-17 11:04:17,946:INFO:Initializing create_model()
2023-09-17 11:04:17,946:INFO:create_model(estimator=knn, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs=None, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7fb0c4031690>, kwargs={})
2023-09-17 11:04:17,946:INFO:Checking exceptions
2023-09-17 11:04:17,946:INFO:Importing libraries
2023-09-17 11:04:17,946:INFO:Copying training dataset
2023-09-17 11:04:18,000:INFO:Defining folds
2023-09-17 11:04:18,000:INFO:Declaring metric variables
2023-09-17 11:04:18,010:INFO:Importing untrained model
2023-09-17 11:04:18,020:INFO:K Neighbors Classifier Imported succesfully
2023-09-17 11:04:18,039:INFO:Starting cross validation
2023-09-17 11:04:18,040:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-09-17 11:04:39,935:ERROR:create_model() for knn raised an exception:
2023-09-17 11:04:39,936:ERROR:Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pycaret/internal/tabular.py", line 2176, in compare_models
    refit=False,
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pycaret/internal/tabular.py", line 3125, in create_model_supervised
    error_score=0,
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py", line 248, in cross_validate
    for train, test in cv.split(X, y, groups))
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 1017, in __call__
    self.retrieve()
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 909, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 562, in wrap_future_result
    return future.result(timeout=timeout)
  File "/home/ubuntu/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 430, in result
    self._condition.wait(timeout)
  File "/home/ubuntu/anaconda3/lib/python3.7/threading.py", line 296, in wait
    waiter.acquire()
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pycaret/internal/tabular.py", line 2195, in compare_models
    refit=False,
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pycaret/internal/tabular.py", line 3125, in create_model_supervised
    error_score=0,
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py", line 248, in cross_validate
    for train, test in cv.split(X, y, groups))
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 1017, in __call__
    self.retrieve()
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 909, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 562, in wrap_future_result
    return future.result(timeout=timeout)
  File "/home/ubuntu/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 430, in result
    self._condition.wait(timeout)
  File "/home/ubuntu/anaconda3/lib/python3.7/threading.py", line 296, in wait
    waiter.acquire()
KeyboardInterrupt

2023-09-17 11:04:39,938:INFO:Initializing Naive Bayes
2023-09-17 11:04:39,938:INFO:Total runtime is 26.463213411966958 minutes
2023-09-17 11:04:39,950:INFO:SubProcess create_model() called ==================================
2023-09-17 11:04:39,951:INFO:Initializing create_model()
2023-09-17 11:04:39,951:INFO:create_model(estimator=nb, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7fb0c4031690>, kwargs={})
2023-09-17 11:04:39,951:INFO:Checking exceptions
2023-09-17 11:04:39,951:INFO:Importing libraries
2023-09-17 11:04:39,951:INFO:Copying training dataset
2023-09-17 11:04:40,004:INFO:Defining folds
2023-09-17 11:04:40,004:INFO:Declaring metric variables
2023-09-17 11:04:40,014:INFO:Importing untrained model
2023-09-17 11:04:40,023:INFO:Naive Bayes Imported succesfully
2023-09-17 11:04:40,042:INFO:Starting cross validation
2023-09-17 11:04:40,043:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-09-17 11:04:43,319:WARNING:create_model() for nb raised an exception or returned all 0.0, trying without fit_kwargs:
2023-09-17 11:04:43,319:WARNING:Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pycaret/internal/tabular.py", line 2176, in compare_models
    refit=False,
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pycaret/internal/tabular.py", line 3125, in create_model_supervised
    error_score=0,
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py", line 248, in cross_validate
    for train, test in cv.split(X, y, groups))
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 1017, in __call__
    self.retrieve()
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 909, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 562, in wrap_future_result
    return future.result(timeout=timeout)
  File "/home/ubuntu/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 430, in result
    self._condition.wait(timeout)
  File "/home/ubuntu/anaconda3/lib/python3.7/threading.py", line 296, in wait
    waiter.acquire()
KeyboardInterrupt

2023-09-17 11:04:43,321:INFO:Initializing create_model()
2023-09-17 11:04:43,321:INFO:create_model(estimator=nb, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs=None, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7fb0c4031690>, kwargs={})
2023-09-17 11:04:43,321:INFO:Checking exceptions
2023-09-17 11:04:43,321:INFO:Importing libraries
2023-09-17 11:04:43,321:INFO:Copying training dataset
2023-09-17 11:04:43,378:INFO:Defining folds
2023-09-17 11:04:43,378:INFO:Declaring metric variables
2023-09-17 11:04:43,388:INFO:Importing untrained model
2023-09-17 11:04:43,397:INFO:Naive Bayes Imported succesfully
2023-09-17 11:04:43,415:INFO:Starting cross validation
2023-09-17 11:04:43,416:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-09-17 11:04:47,079:ERROR:create_model() for nb raised an exception:
2023-09-17 11:04:47,080:ERROR:Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pycaret/internal/tabular.py", line 2176, in compare_models
    refit=False,
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pycaret/internal/tabular.py", line 3125, in create_model_supervised
    error_score=0,
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py", line 248, in cross_validate
    for train, test in cv.split(X, y, groups))
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 1017, in __call__
    self.retrieve()
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 909, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 562, in wrap_future_result
    return future.result(timeout=timeout)
  File "/home/ubuntu/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 430, in result
    self._condition.wait(timeout)
  File "/home/ubuntu/anaconda3/lib/python3.7/threading.py", line 296, in wait
    waiter.acquire()
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pycaret/internal/tabular.py", line 2195, in compare_models
    refit=False,
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pycaret/internal/tabular.py", line 3125, in create_model_supervised
    error_score=0,
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py", line 248, in cross_validate
    for train, test in cv.split(X, y, groups))
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 1017, in __call__
    self.retrieve()
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 909, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 562, in wrap_future_result
    return future.result(timeout=timeout)
  File "/home/ubuntu/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 430, in result
    self._condition.wait(timeout)
  File "/home/ubuntu/anaconda3/lib/python3.7/threading.py", line 296, in wait
    waiter.acquire()
KeyboardInterrupt

2023-09-17 11:04:47,081:INFO:Initializing Decision Tree Classifier
2023-09-17 11:04:47,082:INFO:Total runtime is 26.582278740406036 minutes
2023-09-17 11:04:47,093:INFO:SubProcess create_model() called ==================================
2023-09-17 11:04:47,094:INFO:Initializing create_model()
2023-09-17 11:04:47,094:INFO:create_model(estimator=dt, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7fb0c4031690>, kwargs={})
2023-09-17 11:04:47,094:INFO:Checking exceptions
2023-09-17 11:04:47,094:INFO:Importing libraries
2023-09-17 11:04:47,094:INFO:Copying training dataset
2023-09-17 11:04:47,147:INFO:Defining folds
2023-09-17 11:04:47,147:INFO:Declaring metric variables
2023-09-17 11:04:47,156:INFO:Importing untrained model
2023-09-17 11:04:47,165:INFO:Decision Tree Classifier Imported succesfully
2023-09-17 11:04:47,182:INFO:Starting cross validation
2023-09-17 11:04:47,183:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-09-17 11:04:49,814:WARNING:create_model() for dt raised an exception or returned all 0.0, trying without fit_kwargs:
2023-09-17 11:04:49,814:WARNING:Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pycaret/internal/tabular.py", line 2176, in compare_models
    refit=False,
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pycaret/internal/tabular.py", line 3125, in create_model_supervised
    error_score=0,
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py", line 248, in cross_validate
    for train, test in cv.split(X, y, groups))
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 1017, in __call__
    self.retrieve()
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 909, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 562, in wrap_future_result
    return future.result(timeout=timeout)
  File "/home/ubuntu/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 430, in result
    self._condition.wait(timeout)
  File "/home/ubuntu/anaconda3/lib/python3.7/threading.py", line 296, in wait
    waiter.acquire()
KeyboardInterrupt

2023-09-17 11:04:49,815:INFO:Initializing create_model()
2023-09-17 11:04:49,816:INFO:create_model(estimator=dt, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs=None, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7fb0c4031690>, kwargs={})
2023-09-17 11:04:49,816:INFO:Checking exceptions
2023-09-17 11:04:49,816:INFO:Importing libraries
2023-09-17 11:04:49,816:INFO:Copying training dataset
2023-09-17 11:04:49,874:INFO:Defining folds
2023-09-17 11:04:49,874:INFO:Declaring metric variables
2023-09-17 11:04:49,885:INFO:Importing untrained model
2023-09-17 11:04:49,894:INFO:Decision Tree Classifier Imported succesfully
2023-09-17 11:04:49,912:INFO:Starting cross validation
2023-09-17 11:04:49,913:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-09-17 11:04:51,776:ERROR:create_model() for dt raised an exception:
2023-09-17 11:04:51,777:ERROR:Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pycaret/internal/tabular.py", line 2176, in compare_models
    refit=False,
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pycaret/internal/tabular.py", line 3125, in create_model_supervised
    error_score=0,
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py", line 248, in cross_validate
    for train, test in cv.split(X, y, groups))
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 1017, in __call__
    self.retrieve()
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 909, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 562, in wrap_future_result
    return future.result(timeout=timeout)
  File "/home/ubuntu/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 430, in result
    self._condition.wait(timeout)
  File "/home/ubuntu/anaconda3/lib/python3.7/threading.py", line 296, in wait
    waiter.acquire()
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pycaret/internal/tabular.py", line 2195, in compare_models
    refit=False,
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pycaret/internal/tabular.py", line 3125, in create_model_supervised
    error_score=0,
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py", line 248, in cross_validate
    for train, test in cv.split(X, y, groups))
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 1017, in __call__
    self.retrieve()
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 909, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 562, in wrap_future_result
    return future.result(timeout=timeout)
  File "/home/ubuntu/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 430, in result
    self._condition.wait(timeout)
  File "/home/ubuntu/anaconda3/lib/python3.7/threading.py", line 296, in wait
    waiter.acquire()
KeyboardInterrupt

2023-09-17 11:04:51,778:INFO:Initializing SVM - Linear Kernel
2023-09-17 11:04:51,779:INFO:Total runtime is 26.660561943054198 minutes
2023-09-17 11:04:51,790:INFO:SubProcess create_model() called ==================================
2023-09-17 11:04:51,791:INFO:Initializing create_model()
2023-09-17 11:04:51,791:INFO:create_model(estimator=svm, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7fb0c4031690>, kwargs={})
2023-09-17 11:04:51,791:INFO:Checking exceptions
2023-09-17 11:04:51,791:INFO:Importing libraries
2023-09-17 11:04:51,791:INFO:Copying training dataset
2023-09-17 11:04:51,844:INFO:Defining folds
2023-09-17 11:04:51,845:INFO:Declaring metric variables
2023-09-17 11:04:51,854:INFO:Importing untrained model
2023-09-17 11:04:51,863:INFO:SVM - Linear Kernel Imported succesfully
2023-09-17 11:04:51,881:INFO:Starting cross validation
2023-09-17 11:04:51,882:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-09-17 11:04:53,685:WARNING:create_model() for svm raised an exception or returned all 0.0, trying without fit_kwargs:
2023-09-17 11:04:53,685:WARNING:Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pycaret/internal/tabular.py", line 2176, in compare_models
    refit=False,
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pycaret/internal/tabular.py", line 3125, in create_model_supervised
    error_score=0,
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py", line 248, in cross_validate
    for train, test in cv.split(X, y, groups))
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 1017, in __call__
    self.retrieve()
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 909, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 562, in wrap_future_result
    return future.result(timeout=timeout)
  File "/home/ubuntu/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 430, in result
    self._condition.wait(timeout)
  File "/home/ubuntu/anaconda3/lib/python3.7/threading.py", line 296, in wait
    waiter.acquire()
KeyboardInterrupt

2023-09-17 11:04:53,687:INFO:Initializing create_model()
2023-09-17 11:04:53,687:INFO:create_model(estimator=svm, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs=None, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7fb0c4031690>, kwargs={})
2023-09-17 11:04:53,687:INFO:Checking exceptions
2023-09-17 11:04:53,687:INFO:Importing libraries
2023-09-17 11:04:53,687:INFO:Copying training dataset
2023-09-17 11:04:53,745:INFO:Defining folds
2023-09-17 11:04:53,746:INFO:Declaring metric variables
2023-09-17 11:04:53,757:INFO:Importing untrained model
2023-09-17 11:04:53,766:INFO:SVM - Linear Kernel Imported succesfully
2023-09-17 11:04:53,784:INFO:Starting cross validation
2023-09-17 11:04:53,785:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-09-17 11:04:55,357:ERROR:create_model() for svm raised an exception:
2023-09-17 11:04:55,358:ERROR:Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pycaret/internal/tabular.py", line 2176, in compare_models
    refit=False,
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pycaret/internal/tabular.py", line 3125, in create_model_supervised
    error_score=0,
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py", line 248, in cross_validate
    for train, test in cv.split(X, y, groups))
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 1017, in __call__
    self.retrieve()
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 909, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 562, in wrap_future_result
    return future.result(timeout=timeout)
  File "/home/ubuntu/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 430, in result
    self._condition.wait(timeout)
  File "/home/ubuntu/anaconda3/lib/python3.7/threading.py", line 296, in wait
    waiter.acquire()
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pycaret/internal/tabular.py", line 2195, in compare_models
    refit=False,
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pycaret/internal/tabular.py", line 3125, in create_model_supervised
    error_score=0,
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py", line 248, in cross_validate
    for train, test in cv.split(X, y, groups))
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 1017, in __call__
    self.retrieve()
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 909, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 562, in wrap_future_result
    return future.result(timeout=timeout)
  File "/home/ubuntu/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 430, in result
    self._condition.wait(timeout)
  File "/home/ubuntu/anaconda3/lib/python3.7/threading.py", line 296, in wait
    waiter.acquire()
KeyboardInterrupt

2023-09-17 11:04:55,360:INFO:Initializing Ridge Classifier
2023-09-17 11:04:55,360:INFO:Total runtime is 26.720248389244077 minutes
2023-09-17 11:04:55,372:INFO:SubProcess create_model() called ==================================
2023-09-17 11:04:55,373:INFO:Initializing create_model()
2023-09-17 11:04:55,373:INFO:create_model(estimator=ridge, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7fb0c4031690>, kwargs={})
2023-09-17 11:04:55,373:INFO:Checking exceptions
2023-09-17 11:04:55,373:INFO:Importing libraries
2023-09-17 11:04:55,373:INFO:Copying training dataset
2023-09-17 11:04:55,426:INFO:Defining folds
2023-09-17 11:04:55,426:INFO:Declaring metric variables
2023-09-17 11:04:55,435:INFO:Importing untrained model
2023-09-17 11:04:55,445:INFO:Ridge Classifier Imported succesfully
2023-09-17 11:04:55,462:INFO:Starting cross validation
2023-09-17 11:04:55,463:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-09-17 11:04:56,871:WARNING:create_model() for ridge raised an exception or returned all 0.0, trying without fit_kwargs:
2023-09-17 11:04:56,872:WARNING:Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pycaret/internal/tabular.py", line 2176, in compare_models
    refit=False,
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pycaret/internal/tabular.py", line 3125, in create_model_supervised
    error_score=0,
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py", line 248, in cross_validate
    for train, test in cv.split(X, y, groups))
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 1017, in __call__
    self.retrieve()
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 909, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 562, in wrap_future_result
    return future.result(timeout=timeout)
  File "/home/ubuntu/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 430, in result
    self._condition.wait(timeout)
  File "/home/ubuntu/anaconda3/lib/python3.7/threading.py", line 296, in wait
    waiter.acquire()
KeyboardInterrupt

2023-09-17 11:04:56,873:INFO:Initializing create_model()
2023-09-17 11:04:56,873:INFO:create_model(estimator=ridge, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs=None, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7fb0c4031690>, kwargs={})
2023-09-17 11:04:56,873:INFO:Checking exceptions
2023-09-17 11:04:56,873:INFO:Importing libraries
2023-09-17 11:04:56,873:INFO:Copying training dataset
2023-09-17 11:04:56,930:INFO:Defining folds
2023-09-17 11:04:56,930:INFO:Declaring metric variables
2023-09-17 11:04:56,941:INFO:Importing untrained model
2023-09-17 11:04:56,949:INFO:Ridge Classifier Imported succesfully
2023-09-17 11:04:56,967:INFO:Starting cross validation
2023-09-17 11:04:56,968:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-09-17 11:04:58,170:ERROR:create_model() for ridge raised an exception:
2023-09-17 11:04:58,171:ERROR:joblib.externals.loky.process_executor._RemoteTraceback: 
'''
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 391, in _process_worker
    call_item = call_queue.get(block=True, timeout=timeout)
  File "/home/ubuntu/anaconda3/lib/python3.7/multiprocessing/queues.py", line 99, in get
    if not self._rlock.acquire(block, timeout):
KeyboardInterrupt
'''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pycaret/internal/tabular.py", line 2195, in compare_models
    refit=False,
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pycaret/internal/tabular.py", line 3125, in create_model_supervised
    error_score=0,
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py", line 248, in cross_validate
    for train, test in cv.split(X, y, groups))
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 1017, in __call__
    self.retrieve()
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 909, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 562, in wrap_future_result
    return future.result(timeout=timeout)
  File "/home/ubuntu/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 435, in result
    return self.__get_result()
  File "/home/ubuntu/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
joblib.externals.loky.process_executor.BrokenProcessPool: A task has failed to un-serialize. Please ensure that the arguments of the function are all picklable.

2023-09-17 11:04:58,171:INFO:Initializing Random Forest Classifier
2023-09-17 11:04:58,172:INFO:Total runtime is 26.7671116789182 minutes
2023-09-17 11:04:58,184:INFO:SubProcess create_model() called ==================================
2023-09-17 11:04:58,184:INFO:Initializing create_model()
2023-09-17 11:04:58,184:INFO:create_model(estimator=rf, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7fb0c4031690>, kwargs={})
2023-09-17 11:04:58,184:INFO:Checking exceptions
2023-09-17 11:04:58,185:INFO:Importing libraries
2023-09-17 11:04:58,185:INFO:Copying training dataset
2023-09-17 11:04:58,239:INFO:Defining folds
2023-09-17 11:04:58,239:INFO:Declaring metric variables
2023-09-17 11:04:58,248:INFO:Importing untrained model
2023-09-17 11:04:58,258:INFO:Random Forest Classifier Imported succesfully
2023-09-17 11:04:58,276:INFO:Starting cross validation
2023-09-17 11:04:58,277:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-09-17 11:05:07,873:WARNING:create_model() for rf raised an exception or returned all 0.0, trying without fit_kwargs:
2023-09-17 11:05:07,878:WARNING:Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 909, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 562, in wrap_future_result
    return future.result(timeout=timeout)
  File "/home/ubuntu/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 430, in result
    self._condition.wait(timeout)
  File "/home/ubuntu/anaconda3/lib/python3.7/threading.py", line 296, in wait
    waiter.acquire()
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pycaret/internal/tabular.py", line 2176, in compare_models
    refit=False,
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pycaret/internal/tabular.py", line 3125, in create_model_supervised
    error_score=0,
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py", line 248, in cross_validate
    for train, test in cv.split(X, y, groups))
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 1017, in __call__
    self.retrieve()
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 931, in retrieve
    backend.abort_everything(ensure_ready=ensure_ready)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 579, in abort_everything
    self._workers.shutdown(kill_workers=True)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 1101, in shutdown
    qmt.join()
  File "/home/ubuntu/anaconda3/lib/python3.7/threading.py", line 1044, in join
    self._wait_for_tstate_lock()
  File "/home/ubuntu/anaconda3/lib/python3.7/threading.py", line 1060, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt

2023-09-17 11:05:07,879:INFO:Initializing create_model()
2023-09-17 11:05:07,879:INFO:create_model(estimator=rf, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs=None, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7fb0c4031690>, kwargs={})
2023-09-17 11:05:07,879:INFO:Checking exceptions
2023-09-17 11:05:07,879:INFO:Importing libraries
2023-09-17 11:05:07,879:INFO:Copying training dataset
2023-09-17 11:05:08,103:INFO:Defining folds
2023-09-17 11:05:08,113:INFO:Declaring metric variables
2023-09-17 11:05:08,147:INFO:Importing untrained model
2023-09-17 11:05:08,172:INFO:Random Forest Classifier Imported succesfully
2023-09-17 11:05:08,218:INFO:Starting cross validation
2023-09-17 11:05:08,220:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-09-17 11:05:09,846:ERROR:create_model() for rf raised an exception:
2023-09-17 11:05:09,847:ERROR:Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 909, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 562, in wrap_future_result
    return future.result(timeout=timeout)
  File "/home/ubuntu/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 430, in result
    self._condition.wait(timeout)
  File "/home/ubuntu/anaconda3/lib/python3.7/threading.py", line 296, in wait
    waiter.acquire()
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pycaret/internal/tabular.py", line 2176, in compare_models
    refit=False,
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pycaret/internal/tabular.py", line 3125, in create_model_supervised
    error_score=0,
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py", line 248, in cross_validate
    for train, test in cv.split(X, y, groups))
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 1017, in __call__
    self.retrieve()
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 931, in retrieve
    backend.abort_everything(ensure_ready=ensure_ready)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 579, in abort_everything
    self._workers.shutdown(kill_workers=True)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 1101, in shutdown
    qmt.join()
  File "/home/ubuntu/anaconda3/lib/python3.7/threading.py", line 1044, in join
    self._wait_for_tstate_lock()
  File "/home/ubuntu/anaconda3/lib/python3.7/threading.py", line 1060, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pycaret/internal/tabular.py", line 2195, in compare_models
    refit=False,
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pycaret/internal/tabular.py", line 3125, in create_model_supervised
    error_score=0,
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py", line 248, in cross_validate
    for train, test in cv.split(X, y, groups))
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 1017, in __call__
    self.retrieve()
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 909, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 562, in wrap_future_result
    return future.result(timeout=timeout)
  File "/home/ubuntu/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 430, in result
    self._condition.wait(timeout)
  File "/home/ubuntu/anaconda3/lib/python3.7/threading.py", line 296, in wait
    waiter.acquire()
KeyboardInterrupt

2023-09-17 11:05:09,849:INFO:Initializing Quadratic Discriminant Analysis
2023-09-17 11:05:09,849:INFO:Total runtime is 26.961732073624926 minutes
2023-09-17 11:05:09,861:INFO:SubProcess create_model() called ==================================
2023-09-17 11:05:09,862:INFO:Initializing create_model()
2023-09-17 11:05:09,862:INFO:create_model(estimator=qda, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7fb0c4031690>, kwargs={})
2023-09-17 11:05:09,862:INFO:Checking exceptions
2023-09-17 11:05:09,862:INFO:Importing libraries
2023-09-17 11:05:09,862:INFO:Copying training dataset
2023-09-17 11:05:09,915:INFO:Defining folds
2023-09-17 11:05:09,915:INFO:Declaring metric variables
2023-09-17 11:05:09,924:INFO:Importing untrained model
2023-09-17 11:05:09,933:INFO:Quadratic Discriminant Analysis Imported succesfully
2023-09-17 11:05:09,951:INFO:Starting cross validation
2023-09-17 11:05:09,951:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-09-17 11:05:10,908:WARNING:create_model() for qda raised an exception or returned all 0.0, trying without fit_kwargs:
2023-09-17 11:05:10,917:WARNING:Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pycaret/internal/tabular.py", line 2176, in compare_models
    refit=False,
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pycaret/internal/tabular.py", line 3125, in create_model_supervised
    error_score=0,
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py", line 248, in cross_validate
    for train, test in cv.split(X, y, groups))
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 1004, in __call__
    if self.dispatch_one_batch(iterator):
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 835, in dispatch_one_batch
    self._dispatch(tasks)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 754, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 551, in apply_async
    future = self._workers.submit(SafeFunction(func))
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/externals/loky/reusable_executor.py", line 160, in submit
    fn, *args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 1047, in submit
    self._ensure_executor_running()
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 1021, in _ensure_executor_running
    self._adjust_process_count()
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 1012, in _adjust_process_count
    p.start()
  File "/home/ubuntu/anaconda3/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/externals/loky/backend/process.py", line 39, in _Popen
    return Popen(process_obj)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/externals/loky/backend/popen_loky_posix.py", line 52, in __init__
    self._launch(process_obj)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/externals/loky/backend/popen_loky_posix.py", line 161, in _launch
    with os.fdopen(parent_w, 'wb') as f:
  File "/home/ubuntu/anaconda3/lib/python3.7/os.py", line 1027, in fdopen
    return io.open(fd, *args, **kwargs)
KeyboardInterrupt

2023-09-17 11:05:10,920:INFO:Initializing create_model()
2023-09-17 11:05:10,921:INFO:create_model(estimator=qda, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs=None, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7fb0c4031690>, kwargs={})
2023-09-17 11:05:10,921:INFO:Checking exceptions
2023-09-17 11:05:10,921:INFO:Importing libraries
2023-09-17 11:05:10,921:INFO:Copying training dataset
2023-09-17 11:05:10,991:INFO:Defining folds
2023-09-17 11:05:10,991:INFO:Declaring metric variables
2023-09-17 11:05:11,006:INFO:Importing untrained model
2023-09-17 11:05:11,015:INFO:Quadratic Discriminant Analysis Imported succesfully
2023-09-17 11:05:11,035:INFO:Starting cross validation
2023-09-17 11:05:11,036:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-09-17 11:05:11,468:ERROR:create_model() for qda raised an exception:
2023-09-17 11:05:11,469:ERROR:joblib.externals.loky.process_executor._RemoteTraceback: 
'''
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 391, in _process_worker
    call_item = call_queue.get(block=True, timeout=timeout)
  File "/home/ubuntu/anaconda3/lib/python3.7/multiprocessing/queues.py", line 99, in get
    if not self._rlock.acquire(block, timeout):
KeyboardInterrupt
'''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pycaret/internal/tabular.py", line 2195, in compare_models
    refit=False,
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pycaret/internal/tabular.py", line 3125, in create_model_supervised
    error_score=0,
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py", line 248, in cross_validate
    for train, test in cv.split(X, y, groups))
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 1017, in __call__
    self.retrieve()
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 909, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 562, in wrap_future_result
    return future.result(timeout=timeout)
  File "/home/ubuntu/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 435, in result
    return self.__get_result()
  File "/home/ubuntu/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
joblib.externals.loky.process_executor.BrokenProcessPool: A task has failed to un-serialize. Please ensure that the arguments of the function are all picklable.

2023-09-17 11:05:11,470:INFO:Initializing Ada Boost Classifier
2023-09-17 11:05:11,470:INFO:Total runtime is 26.988748745123544 minutes
2023-09-17 11:05:11,484:INFO:SubProcess create_model() called ==================================
2023-09-17 11:05:11,485:INFO:Initializing create_model()
2023-09-17 11:05:11,485:INFO:create_model(estimator=ada, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7fb0c4031690>, kwargs={})
2023-09-17 11:05:11,485:INFO:Checking exceptions
2023-09-17 11:05:11,485:INFO:Importing libraries
2023-09-17 11:05:11,485:INFO:Copying training dataset
2023-09-17 11:05:11,537:INFO:Defining folds
2023-09-17 11:05:11,538:INFO:Declaring metric variables
2023-09-17 11:05:11,548:INFO:Importing untrained model
2023-09-17 11:05:11,557:INFO:Ada Boost Classifier Imported succesfully
2023-09-17 11:05:11,576:INFO:Starting cross validation
2023-09-17 11:05:11,576:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-09-17 11:05:20,471:WARNING:create_model() for ada raised an exception or returned all 0.0, trying without fit_kwargs:
2023-09-17 11:05:20,472:WARNING:Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pycaret/internal/tabular.py", line 2176, in compare_models
    refit=False,
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pycaret/internal/tabular.py", line 3125, in create_model_supervised
    error_score=0,
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py", line 248, in cross_validate
    for train, test in cv.split(X, y, groups))
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 1017, in __call__
    self.retrieve()
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 909, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 562, in wrap_future_result
    return future.result(timeout=timeout)
  File "/home/ubuntu/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 430, in result
    self._condition.wait(timeout)
  File "/home/ubuntu/anaconda3/lib/python3.7/threading.py", line 296, in wait
    waiter.acquire()
KeyboardInterrupt

2023-09-17 11:05:20,473:INFO:Initializing create_model()
2023-09-17 11:05:20,473:INFO:create_model(estimator=ada, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs=None, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7fb0c4031690>, kwargs={})
2023-09-17 11:05:20,473:INFO:Checking exceptions
2023-09-17 11:05:20,473:INFO:Importing libraries
2023-09-17 11:05:20,473:INFO:Copying training dataset
2023-09-17 11:05:20,529:INFO:Defining folds
2023-09-17 11:05:20,530:INFO:Declaring metric variables
2023-09-17 11:05:20,541:INFO:Importing untrained model
2023-09-17 11:05:20,550:INFO:Ada Boost Classifier Imported succesfully
2023-09-17 11:05:20,569:INFO:Starting cross validation
2023-09-17 11:05:20,569:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-09-17 11:05:26,130:ERROR:create_model() for ada raised an exception:
2023-09-17 11:05:26,131:ERROR:Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pycaret/internal/tabular.py", line 2176, in compare_models
    refit=False,
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pycaret/internal/tabular.py", line 3125, in create_model_supervised
    error_score=0,
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py", line 248, in cross_validate
    for train, test in cv.split(X, y, groups))
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 1017, in __call__
    self.retrieve()
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 909, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 562, in wrap_future_result
    return future.result(timeout=timeout)
  File "/home/ubuntu/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 430, in result
    self._condition.wait(timeout)
  File "/home/ubuntu/anaconda3/lib/python3.7/threading.py", line 296, in wait
    waiter.acquire()
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pycaret/internal/tabular.py", line 2195, in compare_models
    refit=False,
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pycaret/internal/tabular.py", line 3125, in create_model_supervised
    error_score=0,
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py", line 248, in cross_validate
    for train, test in cv.split(X, y, groups))
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 1017, in __call__
    self.retrieve()
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 909, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 562, in wrap_future_result
    return future.result(timeout=timeout)
  File "/home/ubuntu/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 430, in result
    self._condition.wait(timeout)
  File "/home/ubuntu/anaconda3/lib/python3.7/threading.py", line 296, in wait
    waiter.acquire()
KeyboardInterrupt

2023-09-17 11:05:26,132:INFO:Initializing Gradient Boosting Classifier
2023-09-17 11:05:26,132:INFO:Total runtime is 27.233118232091268 minutes
2023-09-17 11:05:26,144:INFO:SubProcess create_model() called ==================================
2023-09-17 11:05:26,145:INFO:Initializing create_model()
2023-09-17 11:05:26,145:INFO:create_model(estimator=gbc, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7fb0c4031690>, kwargs={})
2023-09-17 11:05:26,145:INFO:Checking exceptions
2023-09-17 11:05:26,146:INFO:Importing libraries
2023-09-17 11:05:26,146:INFO:Copying training dataset
2023-09-17 11:05:26,198:INFO:Defining folds
2023-09-17 11:05:26,199:INFO:Declaring metric variables
2023-09-17 11:05:26,209:INFO:Importing untrained model
2023-09-17 11:05:26,219:INFO:Gradient Boosting Classifier Imported succesfully
2023-09-17 11:05:26,240:INFO:Starting cross validation
2023-09-17 11:05:26,241:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-09-17 11:05:28,750:WARNING:create_model() for gbc raised an exception or returned all 0.0, trying without fit_kwargs:
2023-09-17 11:05:28,750:WARNING:Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pycaret/internal/tabular.py", line 2176, in compare_models
    refit=False,
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pycaret/internal/tabular.py", line 3125, in create_model_supervised
    error_score=0,
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py", line 248, in cross_validate
    for train, test in cv.split(X, y, groups))
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 1017, in __call__
    self.retrieve()
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 909, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 562, in wrap_future_result
    return future.result(timeout=timeout)
  File "/home/ubuntu/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 430, in result
    self._condition.wait(timeout)
  File "/home/ubuntu/anaconda3/lib/python3.7/threading.py", line 296, in wait
    waiter.acquire()
KeyboardInterrupt

2023-09-17 11:05:28,751:INFO:Initializing create_model()
2023-09-17 11:05:28,751:INFO:create_model(estimator=gbc, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs=None, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7fb0c4031690>, kwargs={})
2023-09-17 11:05:28,751:INFO:Checking exceptions
2023-09-17 11:05:28,751:INFO:Importing libraries
2023-09-17 11:05:28,751:INFO:Copying training dataset
2023-09-17 11:05:28,807:INFO:Defining folds
2023-09-17 11:05:28,808:INFO:Declaring metric variables
2023-09-17 11:05:28,819:INFO:Importing untrained model
2023-09-17 11:05:28,829:INFO:Gradient Boosting Classifier Imported succesfully
2023-09-17 11:05:28,848:INFO:Starting cross validation
2023-09-17 11:05:28,849:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-09-17 11:05:31,075:ERROR:create_model() for gbc raised an exception:
2023-09-17 11:05:31,076:ERROR:Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pycaret/internal/tabular.py", line 2176, in compare_models
    refit=False,
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pycaret/internal/tabular.py", line 3125, in create_model_supervised
    error_score=0,
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py", line 248, in cross_validate
    for train, test in cv.split(X, y, groups))
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 1017, in __call__
    self.retrieve()
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 909, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 562, in wrap_future_result
    return future.result(timeout=timeout)
  File "/home/ubuntu/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 430, in result
    self._condition.wait(timeout)
  File "/home/ubuntu/anaconda3/lib/python3.7/threading.py", line 296, in wait
    waiter.acquire()
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pycaret/internal/tabular.py", line 2195, in compare_models
    refit=False,
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pycaret/internal/tabular.py", line 3125, in create_model_supervised
    error_score=0,
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py", line 248, in cross_validate
    for train, test in cv.split(X, y, groups))
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 1017, in __call__
    self.retrieve()
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 909, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 562, in wrap_future_result
    return future.result(timeout=timeout)
  File "/home/ubuntu/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 430, in result
    self._condition.wait(timeout)
  File "/home/ubuntu/anaconda3/lib/python3.7/threading.py", line 296, in wait
    waiter.acquire()
KeyboardInterrupt

2023-09-17 11:05:31,077:INFO:Initializing Linear Discriminant Analysis
2023-09-17 11:05:31,078:INFO:Total runtime is 27.315545654296876 minutes
2023-09-17 11:05:31,090:INFO:SubProcess create_model() called ==================================
2023-09-17 11:05:31,091:INFO:Initializing create_model()
2023-09-17 11:05:31,091:INFO:create_model(estimator=lda, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7fb0c4031690>, kwargs={})
2023-09-17 11:05:31,091:INFO:Checking exceptions
2023-09-17 11:05:31,091:INFO:Importing libraries
2023-09-17 11:05:31,091:INFO:Copying training dataset
2023-09-17 11:05:31,144:INFO:Defining folds
2023-09-17 11:05:31,144:INFO:Declaring metric variables
2023-09-17 11:05:31,153:INFO:Importing untrained model
2023-09-17 11:05:31,162:INFO:Linear Discriminant Analysis Imported succesfully
2023-09-17 11:05:31,180:INFO:Starting cross validation
2023-09-17 11:05:31,181:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-09-17 11:05:33,492:WARNING:create_model() for lda raised an exception or returned all 0.0, trying without fit_kwargs:
2023-09-17 11:05:33,493:WARNING:Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pycaret/internal/tabular.py", line 2176, in compare_models
    refit=False,
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pycaret/internal/tabular.py", line 3125, in create_model_supervised
    error_score=0,
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py", line 248, in cross_validate
    for train, test in cv.split(X, y, groups))
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 1017, in __call__
    self.retrieve()
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 909, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 562, in wrap_future_result
    return future.result(timeout=timeout)
  File "/home/ubuntu/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 430, in result
    self._condition.wait(timeout)
  File "/home/ubuntu/anaconda3/lib/python3.7/threading.py", line 296, in wait
    waiter.acquire()
KeyboardInterrupt

2023-09-17 11:05:33,494:INFO:Initializing create_model()
2023-09-17 11:05:33,494:INFO:create_model(estimator=lda, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs=None, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7fb0c4031690>, kwargs={})
2023-09-17 11:05:33,495:INFO:Checking exceptions
2023-09-17 11:05:33,495:INFO:Importing libraries
2023-09-17 11:05:33,495:INFO:Copying training dataset
2023-09-17 11:05:33,551:INFO:Defining folds
2023-09-17 11:05:33,551:INFO:Declaring metric variables
2023-09-17 11:05:33,561:INFO:Importing untrained model
2023-09-17 11:05:33,571:INFO:Linear Discriminant Analysis Imported succesfully
2023-09-17 11:05:33,589:INFO:Starting cross validation
2023-09-17 11:05:33,589:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-09-17 11:05:35,545:ERROR:create_model() for lda raised an exception:
2023-09-17 11:05:35,547:ERROR:Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pycaret/internal/tabular.py", line 2176, in compare_models
    refit=False,
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pycaret/internal/tabular.py", line 3125, in create_model_supervised
    error_score=0,
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py", line 248, in cross_validate
    for train, test in cv.split(X, y, groups))
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 1017, in __call__
    self.retrieve()
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 909, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 562, in wrap_future_result
    return future.result(timeout=timeout)
  File "/home/ubuntu/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 430, in result
    self._condition.wait(timeout)
  File "/home/ubuntu/anaconda3/lib/python3.7/threading.py", line 296, in wait
    waiter.acquire()
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pycaret/internal/tabular.py", line 2195, in compare_models
    refit=False,
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pycaret/internal/tabular.py", line 3125, in create_model_supervised
    error_score=0,
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py", line 248, in cross_validate
    for train, test in cv.split(X, y, groups))
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 1017, in __call__
    self.retrieve()
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 909, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 562, in wrap_future_result
    return future.result(timeout=timeout)
  File "/home/ubuntu/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 430, in result
    self._condition.wait(timeout)
  File "/home/ubuntu/anaconda3/lib/python3.7/threading.py", line 296, in wait
    waiter.acquire()
KeyboardInterrupt

2023-09-17 11:05:35,548:INFO:Initializing Extra Trees Classifier
2023-09-17 11:05:35,548:INFO:Total runtime is 27.39004970788956 minutes
2023-09-17 11:05:35,560:INFO:SubProcess create_model() called ==================================
2023-09-17 11:05:35,561:INFO:Initializing create_model()
2023-09-17 11:05:35,561:INFO:create_model(estimator=et, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7fb0c4031690>, kwargs={})
2023-09-17 11:05:35,561:INFO:Checking exceptions
2023-09-17 11:05:35,561:INFO:Importing libraries
2023-09-17 11:05:35,562:INFO:Copying training dataset
2023-09-17 11:05:35,615:INFO:Defining folds
2023-09-17 11:05:35,615:INFO:Declaring metric variables
2023-09-17 11:05:35,624:INFO:Importing untrained model
2023-09-17 11:05:35,633:INFO:Extra Trees Classifier Imported succesfully
2023-09-17 11:05:35,652:INFO:Starting cross validation
2023-09-17 11:05:35,653:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-09-17 11:05:37,351:WARNING:create_model() for et raised an exception or returned all 0.0, trying without fit_kwargs:
2023-09-17 11:05:37,352:WARNING:Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pycaret/internal/tabular.py", line 2176, in compare_models
    refit=False,
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pycaret/internal/tabular.py", line 3125, in create_model_supervised
    error_score=0,
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py", line 248, in cross_validate
    for train, test in cv.split(X, y, groups))
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 1017, in __call__
    self.retrieve()
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 909, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 562, in wrap_future_result
    return future.result(timeout=timeout)
  File "/home/ubuntu/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 430, in result
    self._condition.wait(timeout)
  File "/home/ubuntu/anaconda3/lib/python3.7/threading.py", line 296, in wait
    waiter.acquire()
KeyboardInterrupt

2023-09-17 11:05:37,352:INFO:Initializing create_model()
2023-09-17 11:05:37,352:INFO:create_model(estimator=et, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs=None, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7fb0c4031690>, kwargs={})
2023-09-17 11:05:37,352:INFO:Checking exceptions
2023-09-17 11:05:37,352:INFO:Importing libraries
2023-09-17 11:05:37,353:INFO:Copying training dataset
2023-09-17 11:05:37,409:INFO:Defining folds
2023-09-17 11:05:37,409:INFO:Declaring metric variables
2023-09-17 11:05:37,420:INFO:Importing untrained model
2023-09-17 11:05:37,429:INFO:Extra Trees Classifier Imported succesfully
2023-09-17 11:05:37,447:INFO:Starting cross validation
2023-09-17 11:05:37,448:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-09-17 11:05:39,916:ERROR:create_model() for et raised an exception:
2023-09-17 11:05:39,917:ERROR:Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pycaret/internal/tabular.py", line 2176, in compare_models
    refit=False,
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pycaret/internal/tabular.py", line 3125, in create_model_supervised
    error_score=0,
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py", line 248, in cross_validate
    for train, test in cv.split(X, y, groups))
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 1017, in __call__
    self.retrieve()
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 909, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 562, in wrap_future_result
    return future.result(timeout=timeout)
  File "/home/ubuntu/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 430, in result
    self._condition.wait(timeout)
  File "/home/ubuntu/anaconda3/lib/python3.7/threading.py", line 296, in wait
    waiter.acquire()
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pycaret/internal/tabular.py", line 2195, in compare_models
    refit=False,
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pycaret/internal/tabular.py", line 3125, in create_model_supervised
    error_score=0,
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py", line 248, in cross_validate
    for train, test in cv.split(X, y, groups))
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 1017, in __call__
    self.retrieve()
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 909, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 562, in wrap_future_result
    return future.result(timeout=timeout)
  File "/home/ubuntu/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 430, in result
    self._condition.wait(timeout)
  File "/home/ubuntu/anaconda3/lib/python3.7/threading.py", line 296, in wait
    waiter.acquire()
KeyboardInterrupt

2023-09-17 11:05:39,918:INFO:Initializing Extreme Gradient Boosting
2023-09-17 11:05:39,919:INFO:Total runtime is 27.462895031770074 minutes
2023-09-17 11:05:39,931:INFO:SubProcess create_model() called ==================================
2023-09-17 11:05:39,931:INFO:Initializing create_model()
2023-09-17 11:05:39,932:INFO:create_model(estimator=xgboost, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7fb0c4031690>, kwargs={})
2023-09-17 11:05:39,932:INFO:Checking exceptions
2023-09-17 11:05:39,932:INFO:Importing libraries
2023-09-17 11:05:39,932:INFO:Copying training dataset
2023-09-17 11:05:39,985:INFO:Defining folds
2023-09-17 11:05:39,986:INFO:Declaring metric variables
2023-09-17 11:05:39,995:INFO:Importing untrained model
2023-09-17 11:05:40,004:INFO:Extreme Gradient Boosting Imported succesfully
2023-09-17 11:05:40,022:INFO:Starting cross validation
2023-09-17 11:05:40,024:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-09-17 11:05:41,003:WARNING:create_model() for xgboost raised an exception or returned all 0.0, trying without fit_kwargs:
2023-09-17 11:05:41,008:WARNING:Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pycaret/internal/tabular.py", line 2176, in compare_models
    refit=False,
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pycaret/internal/tabular.py", line 3125, in create_model_supervised
    error_score=0,
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py", line 248, in cross_validate
    for train, test in cv.split(X, y, groups))
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 1004, in __call__
    if self.dispatch_one_batch(iterator):
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 835, in dispatch_one_batch
    self._dispatch(tasks)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 754, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 551, in apply_async
    future = self._workers.submit(SafeFunction(func))
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/externals/loky/reusable_executor.py", line 160, in submit
    fn, *args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 1047, in submit
    self._ensure_executor_running()
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 1021, in _ensure_executor_running
    self._adjust_process_count()
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 1012, in _adjust_process_count
    p.start()
  File "/home/ubuntu/anaconda3/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/externals/loky/backend/process.py", line 39, in _Popen
    return Popen(process_obj)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/externals/loky/backend/popen_loky_posix.py", line 48, in __init__
    sys.stdout.flush()
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ipykernel/iostream.py", line 343, in flush
    self.pub_thread.schedule(self._flush)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ipykernel/iostream.py", line 197, in schedule
    def schedule(self, f):
KeyboardInterrupt

2023-09-17 11:05:41,009:INFO:Initializing create_model()
2023-09-17 11:05:41,010:INFO:create_model(estimator=xgboost, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs=None, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7fb0c4031690>, kwargs={})
2023-09-17 11:05:41,010:INFO:Checking exceptions
2023-09-17 11:05:41,010:INFO:Importing libraries
2023-09-17 11:05:41,011:INFO:Copying training dataset
2023-09-17 11:05:41,077:INFO:Defining folds
2023-09-17 11:05:41,077:INFO:Declaring metric variables
2023-09-17 11:05:41,088:INFO:Importing untrained model
2023-09-17 11:05:41,098:INFO:Extreme Gradient Boosting Imported succesfully
2023-09-17 11:05:41,116:INFO:Starting cross validation
2023-09-17 11:05:41,118:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-09-17 11:05:41,446:ERROR:create_model() for xgboost raised an exception:
2023-09-17 11:05:41,448:ERROR:joblib.externals.loky.process_executor._RemoteTraceback: 
'''
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 391, in _process_worker
    call_item = call_queue.get(block=True, timeout=timeout)
  File "/home/ubuntu/anaconda3/lib/python3.7/multiprocessing/queues.py", line 99, in get
    if not self._rlock.acquire(block, timeout):
KeyboardInterrupt
'''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pycaret/internal/tabular.py", line 2195, in compare_models
    refit=False,
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pycaret/internal/tabular.py", line 3125, in create_model_supervised
    error_score=0,
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py", line 248, in cross_validate
    for train, test in cv.split(X, y, groups))
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 1017, in __call__
    self.retrieve()
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 909, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 562, in wrap_future_result
    return future.result(timeout=timeout)
  File "/home/ubuntu/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 435, in result
    return self.__get_result()
  File "/home/ubuntu/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
joblib.externals.loky.process_executor.BrokenProcessPool: A task has failed to un-serialize. Please ensure that the arguments of the function are all picklable.

2023-09-17 11:05:41,448:INFO:Initializing Light Gradient Boosting Machine
2023-09-17 11:05:41,448:INFO:Total runtime is 27.488382991154992 minutes
2023-09-17 11:05:41,462:INFO:SubProcess create_model() called ==================================
2023-09-17 11:05:41,463:INFO:Initializing create_model()
2023-09-17 11:05:41,463:INFO:create_model(estimator=lightgbm, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7fb0c4031690>, kwargs={})
2023-09-17 11:05:41,464:INFO:Checking exceptions
2023-09-17 11:05:41,464:INFO:Importing libraries
2023-09-17 11:05:41,464:INFO:Copying training dataset
2023-09-17 11:05:41,521:INFO:Defining folds
2023-09-17 11:05:41,522:INFO:Declaring metric variables
2023-09-17 11:05:41,532:INFO:Importing untrained model
2023-09-17 11:05:41,542:INFO:Light Gradient Boosting Machine Imported succesfully
2023-09-17 11:05:41,562:INFO:Starting cross validation
2023-09-17 11:05:41,563:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-09-17 11:05:43,076:WARNING:create_model() for lightgbm raised an exception or returned all 0.0, trying without fit_kwargs:
2023-09-17 11:05:43,077:WARNING:Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pycaret/internal/tabular.py", line 2176, in compare_models
    refit=False,
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pycaret/internal/tabular.py", line 3125, in create_model_supervised
    error_score=0,
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py", line 248, in cross_validate
    for train, test in cv.split(X, y, groups))
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 1017, in __call__
    self.retrieve()
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 909, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 562, in wrap_future_result
    return future.result(timeout=timeout)
  File "/home/ubuntu/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 430, in result
    self._condition.wait(timeout)
  File "/home/ubuntu/anaconda3/lib/python3.7/threading.py", line 296, in wait
    waiter.acquire()
KeyboardInterrupt

2023-09-17 11:05:43,079:INFO:Initializing create_model()
2023-09-17 11:05:43,079:INFO:create_model(estimator=lightgbm, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs=None, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7fb0c4031690>, kwargs={})
2023-09-17 11:05:43,079:INFO:Checking exceptions
2023-09-17 11:05:43,079:INFO:Importing libraries
2023-09-17 11:05:43,079:INFO:Copying training dataset
2023-09-17 11:05:43,132:INFO:Defining folds
2023-09-17 11:05:43,133:INFO:Declaring metric variables
2023-09-17 11:05:43,144:INFO:Importing untrained model
2023-09-17 11:05:43,153:INFO:Light Gradient Boosting Machine Imported succesfully
2023-09-17 11:05:43,173:INFO:Starting cross validation
2023-09-17 11:05:43,173:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-09-17 11:05:45,344:ERROR:create_model() for lightgbm raised an exception:
2023-09-17 11:05:45,345:ERROR:Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pycaret/internal/tabular.py", line 2176, in compare_models
    refit=False,
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pycaret/internal/tabular.py", line 3125, in create_model_supervised
    error_score=0,
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py", line 248, in cross_validate
    for train, test in cv.split(X, y, groups))
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 1017, in __call__
    self.retrieve()
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 909, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 562, in wrap_future_result
    return future.result(timeout=timeout)
  File "/home/ubuntu/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 430, in result
    self._condition.wait(timeout)
  File "/home/ubuntu/anaconda3/lib/python3.7/threading.py", line 296, in wait
    waiter.acquire()
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pycaret/internal/tabular.py", line 2195, in compare_models
    refit=False,
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/pycaret/internal/tabular.py", line 3125, in create_model_supervised
    error_score=0,
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py", line 248, in cross_validate
    for train, test in cv.split(X, y, groups))
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 1017, in __call__
    self.retrieve()
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 909, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 562, in wrap_future_result
    return future.result(timeout=timeout)
  File "/home/ubuntu/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 430, in result
    self._condition.wait(timeout)
  File "/home/ubuntu/anaconda3/lib/python3.7/threading.py", line 296, in wait
    waiter.acquire()
KeyboardInterrupt

2023-09-17 11:05:45,372:INFO:Initializing create_model()
2023-09-17 11:05:45,372:INFO:create_model(estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=123, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False), fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=False, predict=False, fit_kwargs={}, groups=None, refit=True, verbose=False, system=False, metrics=None, display=None, kwargs={})
2023-09-17 11:05:45,373:INFO:Checking exceptions
2023-09-17 11:05:45,373:INFO:Importing libraries
2023-09-17 11:05:45,373:INFO:Copying training dataset
2023-09-17 11:05:45,425:INFO:Defining folds
2023-09-17 11:05:45,425:INFO:Declaring metric variables
2023-09-17 11:05:45,425:INFO:Importing untrained model
2023-09-17 11:05:45,425:INFO:Declaring custom model
2023-09-17 11:05:45,426:INFO:Logistic Regression Imported succesfully
2023-09-17 11:05:45,426:INFO:Cross validation set to False
2023-09-17 11:05:45,426:INFO:Fitting Model
2023-09-17 11:06:00,864:INFO:PyCaret Supervised Module
2023-09-17 11:06:00,864:INFO:ML Usecase: classification
2023-09-17 11:06:00,864:INFO:version 2.3.3
2023-09-17 11:06:00,864:INFO:Initializing setup()
2023-09-17 11:06:00,864:INFO:setup(target=default, ml_usecase=classification, available_plots={'parameter': 'Hyperparameters', 'auc': 'AUC', 'confusion_matrix': 'Confusion Matrix', 'threshold': 'Threshold', 'pr': 'Precision Recall', 'error': 'Prediction Error', 'class_report': 'Class Report', 'rfe': 'Feature Selection', 'learning': 'Learning Curve', 'manifold': 'Manifold Learning', 'calibration': 'Calibration Curve', 'vc': 'Validation Curve', 'dimension': 'Dimensions', 'feature': 'Feature Importance', 'feature_all': 'Feature Importance (All)', 'boundary': 'Decision Boundary', 'lift': 'Lift Chart', 'gain': 'Gain Chart', 'tree': 'Decision Tree', 'ks': 'KS Statistic Plot'}, train_size=0.7, test_data=None, preprocess=True, imputation_type=simple, iterative_imputation_iters=5, categorical_features=None, categorical_imputation=constant, categorical_iterative_imputer=lightgbm, ordinal_features=None, high_cardinality_features=None, high_cardinality_method=frequency, numeric_features=None, numeric_imputation=mean, numeric_iterative_imputer=lightgbm, date_features=None, ignore_features=None, normalize=False, normalize_method=zscore, transformation=False, transformation_method=yeo-johnson, handle_unknown_categorical=True, unknown_categorical_method=least_frequent, pca=False, pca_method=linear, pca_components=None, ignore_low_variance=False, combine_rare_levels=False, rare_level_threshold=0.1, bin_numeric_features=None, remove_outliers=False, outliers_threshold=0.05, remove_multicollinearity=False, multicollinearity_threshold=0.9, remove_perfect_collinearity=True, create_clusters=False, cluster_iter=20, polynomial_features=False, polynomial_degree=2, trigonometry_features=False, polynomial_threshold=0.1, group_features=None, group_names=None, feature_selection=False, feature_selection_threshold=0.8, feature_selection_method=classic, feature_interaction=False, feature_ratio=False, interaction_threshold=0.01, fix_imbalance=False, fix_imbalance_method=None, transform_target=False, transform_target_method=box-cox, data_split_shuffle=True, data_split_stratify=False, fold_strategy=stratifiedkfold, fold=10, fold_shuffle=False, fold_groups=None, n_jobs=-1, use_gpu=False, custom_pipeline=None, html=True, session_id=123, log_experiment=False, experiment_name=None, log_plots=False, log_profile=False, log_data=False, silent=False, verbose=True, profile=False, profile_kwargs=None, display=None)
2023-09-17 11:06:00,864:INFO:Checking environment
2023-09-17 11:06:00,864:INFO:python_version: 3.7.6
2023-09-17 11:06:00,865:INFO:python_build: ('default', 'Jan  8 2020 19:59:22')
2023-09-17 11:06:00,865:INFO:machine: x86_64
2023-09-17 11:06:00,865:INFO:platform: Linux-5.4.0-1103-aws-x86_64-with-debian-buster-sid
2023-09-17 11:06:00,865:INFO:Memory: svmem(total=67415244800, available=54305824768, percent=19.4, used=12366880768, free=29439856640, active=22978965504, inactive=12038344704, buffers=1893019648, cached=23715487744, shared=1130496, slab=2602377216)
2023-09-17 11:06:00,866:INFO:Physical Core: 8
2023-09-17 11:06:00,866:INFO:Logical Core: 16
2023-09-17 11:06:00,866:INFO:Checking libraries
2023-09-17 11:06:00,867:INFO:pd==1.3.5
2023-09-17 11:06:00,867:INFO:numpy==1.21.6
2023-09-17 11:06:00,867:INFO:sklearn==0.23.2
2023-09-17 11:06:00,867:INFO:lightgbm==3.2.1
2023-09-17 11:06:00,867:WARNING:catboost not found
2023-09-17 11:06:00,867:INFO:xgboost==1.6.1
2023-09-17 11:06:00,867:INFO:mlflow==1.20.1
2023-09-17 11:06:00,867:INFO:Checking Exceptions
2023-09-17 11:06:00,868:INFO:Declaring global variables
2023-09-17 11:06:00,868:INFO:USI: b9fc
2023-09-17 11:06:00,868:INFO:pycaret_globals: {'fold_groups_param_full', 'stratify_param', '_ml_usecase', 'USI', '_gpu_n_jobs_param', 'n_jobs_param', 'create_model_container', 'imputation_regressor', '_all_metrics', '_available_plots', '_internal_pipeline', 'fold_groups_param', 'exp_name_log', 'data_before_preprocess', 'log_plots_param', 'seed', 'X_test', '_all_models', '_all_models_internal', 'html_param', 'fold_param', 'transform_target_param', 'iterative_imputation_iters_param', 'X', 'pycaret_globals', 'experiment__', 'master_model_container', 'gpu_param', 'target_param', 'logging_param', 'y_train', 'fold_shuffle_param', 'fix_imbalance_param', 'display_container', 'imputation_classifier', 'fold_generator', 'y_test', 'y', 'prep_pipe', 'X_train', 'transform_target_method_param', 'fix_imbalance_method_param'}
2023-09-17 11:06:00,868:INFO:Preparing display monitor
2023-09-17 11:06:00,868:INFO:Preparing display monitor
2023-09-17 11:06:00,882:INFO:Importing libraries
2023-09-17 11:06:00,883:INFO:Copying data for preprocessing
2023-09-17 11:06:00,941:INFO:Declaring preprocessing parameters
2023-09-17 11:06:01,092:INFO:Creating preprocessing pipeline
2023-09-17 11:06:03,300:INFO:Preprocessing pipeline created successfully
2023-09-17 11:06:03,301:ERROR:(Process Exit): setup has been interupted with user command 'quit'. setup must rerun.
2023-09-17 11:06:03,301:INFO:Creating global containers
2023-09-17 11:06:03,301:INFO:Internal pipeline: Pipeline(memory=None, steps=[('empty_step', 'passthrough')], verbose=False)
2023-09-17 11:06:57,566:WARNING:Couldn't import catboost.CatBoostClassifier
2023-09-17 11:06:57,652:WARNING:Couldn't import catboost.CatBoostClassifier
2023-09-17 11:06:57,653:INFO:Creating grid variables
2023-09-17 11:06:57,905:INFO:create_model_container: 0
2023-09-17 11:06:57,906:INFO:master_model_container: 0
2023-09-17 11:06:57,906:INFO:display_container: 1
2023-09-17 11:06:57,911:INFO:Pipeline(memory=None,
         steps=[('dtypes',
                 DataTypes_Auto_infer(categorical_features=[],
                                      display_types=True, features_todrop=[],
                                      id_columns=[],
                                      ml_usecase='classification',
                                      numerical_features=[], target='default',
                                      time_features=[])),
                ('imputer',
                 Simple_Imputer(categorical_strategy='not_available',
                                fill_value_categorical=None,
                                fill_value_numerical=None,
                                numeric_stra...
                ('scaling', 'passthrough'), ('P_transform', 'passthrough'),
                ('binn', 'passthrough'), ('rem_outliers', 'passthrough'),
                ('cluster_all', 'passthrough'),
                ('dummy', Dummify(target='default')),
                ('fix_perfect', Remove_100(target='default')),
                ('clean_names', Clean_Colum_Names()),
                ('feature_select', 'passthrough'), ('fix_multi', 'passthrough'),
                ('dfs', 'passthrough'), ('pca', 'passthrough')],
         verbose=False)
2023-09-17 11:06:57,911:INFO:setup() succesfully completed......................................
2023-09-17 11:08:16,552:INFO:Initializing create_model()
2023-09-17 11:08:16,552:INFO:create_model(estimator=dt, fold=None, round=4, cross_validation=True, predict=True, fit_kwargs=None, groups=None, refit=True, verbose=True, system=True, metrics=None, display=None, kwargs={})
2023-09-17 11:08:16,552:INFO:Checking exceptions
2023-09-17 11:08:16,553:INFO:Preparing display monitor
2023-09-17 11:08:16,573:INFO:Importing libraries
2023-09-17 11:08:16,574:INFO:Copying training dataset
2023-09-17 11:08:16,594:INFO:Defining folds
2023-09-17 11:08:16,594:INFO:Declaring metric variables
2023-09-17 11:08:16,604:INFO:Importing untrained model
2023-09-17 11:08:16,613:INFO:Decision Tree Classifier Imported succesfully
2023-09-17 11:08:16,631:INFO:Starting cross validation
2023-09-17 11:08:16,632:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-09-17 11:08:27,009:INFO:Calculating mean and std
2023-09-17 11:08:27,011:INFO:Creating metrics dataframe
2023-09-17 11:08:27,027:INFO:Finalizing model
2023-09-17 11:08:29,992:INFO:Uploading results into container
2023-09-17 11:08:29,993:INFO:Uploading model into container now
2023-09-17 11:08:30,009:INFO:create_model_container: 1
2023-09-17 11:08:30,009:INFO:master_model_container: 1
2023-09-17 11:08:30,009:INFO:display_container: 2
2023-09-17 11:08:30,009:INFO:DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=123, splitter='best')
2023-09-17 11:08:30,009:INFO:create_model() succesfully completed......................................
2023-09-17 11:12:37,930:INFO:Initializing create_model()
2023-09-17 11:12:37,930:INFO:create_model(estimator=lr, fold=None, round=4, cross_validation=True, predict=True, fit_kwargs=None, groups=None, refit=True, verbose=True, system=True, metrics=None, display=None, kwargs={})
2023-09-17 11:12:37,930:INFO:Checking exceptions
2023-09-17 11:12:37,931:INFO:Preparing display monitor
2023-09-17 11:12:37,951:INFO:Importing libraries
2023-09-17 11:12:37,952:INFO:Copying training dataset
2023-09-17 11:12:37,981:INFO:Defining folds
2023-09-17 11:12:37,982:INFO:Declaring metric variables
2023-09-17 11:12:37,991:INFO:Importing untrained model
2023-09-17 11:12:37,999:INFO:Logistic Regression Imported succesfully
2023-09-17 11:12:38,017:INFO:Starting cross validation
2023-09-17 11:12:38,017:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-09-17 11:13:56,055:INFO:Calculating mean and std
2023-09-17 11:13:56,056:INFO:Creating metrics dataframe
2023-09-17 11:13:56,070:INFO:Finalizing model
2023-09-17 11:14:23,168:INFO:Uploading results into container
2023-09-17 11:14:23,168:INFO:Uploading model into container now
2023-09-17 11:14:23,190:INFO:create_model_container: 2
2023-09-17 11:14:23,190:INFO:master_model_container: 2
2023-09-17 11:14:23,190:INFO:display_container: 3
2023-09-17 11:14:23,191:INFO:LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=123, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)
2023-09-17 11:14:23,191:INFO:create_model() succesfully completed......................................
2023-09-17 11:16:08,382:INFO:Initializing create_model()
2023-09-17 11:16:08,383:INFO:create_model(estimator=xgboost, fold=None, round=4, cross_validation=True, predict=True, fit_kwargs=None, groups=None, refit=True, verbose=True, system=True, metrics=None, display=None, kwargs={})
2023-09-17 11:16:08,383:INFO:Checking exceptions
2023-09-17 11:16:08,383:INFO:Preparing display monitor
2023-09-17 11:16:08,404:INFO:Importing libraries
2023-09-17 11:16:08,404:INFO:Copying training dataset
2023-09-17 11:16:08,423:INFO:Defining folds
2023-09-17 11:16:08,423:INFO:Declaring metric variables
2023-09-17 11:16:08,433:INFO:Importing untrained model
2023-09-17 11:16:08,443:INFO:Extreme Gradient Boosting Imported succesfully
2023-09-17 11:16:08,462:INFO:Starting cross validation
2023-09-17 11:16:08,464:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-09-17 11:20:10,154:INFO:Calculating mean and std
2023-09-17 11:20:10,156:INFO:Creating metrics dataframe
2023-09-17 11:20:10,173:INFO:Finalizing model
2023-09-17 11:20:43,398:INFO:Uploading results into container
2023-09-17 11:20:43,398:INFO:Uploading model into container now
2023-09-17 11:20:43,418:INFO:create_model_container: 3
2023-09-17 11:20:43,418:INFO:master_model_container: 3
2023-09-17 11:20:43,419:INFO:display_container: 4
2023-09-17 11:20:43,422:INFO:XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, gamma=0, gpu_id=-1, grow_policy='depthwise',
              importance_type=None, interaction_constraints='',
              learning_rate=0.300000012, max_bin=256, max_cat_to_onehot=4,
              max_delta_step=0, max_depth=6, max_leaves=0, min_child_weight=1,
              missing=nan, monotone_constraints='()', n_estimators=100,
              n_jobs=-1, num_parallel_tree=1, objective='binary:logistic',
              predictor='auto', random_state=123, reg_alpha=0, ...)
2023-09-17 11:20:43,422:INFO:create_model() succesfully completed......................................
2023-09-17 11:23:56,518:INFO:Initializing tune_model()
2023-09-17 11:23:56,518:INFO:tune_model(estimator=xgboost, fold=None, round=4, n_iter=10, custom_grid=None, optimize=Accuracy, custom_scorer=None, search_library=scikit-learn, search_algorithm=None, early_stopping=False, early_stopping_max_iters=10, choose_better=False, fit_kwargs=None, groups=None, return_tuner=False, verbose=True, tuner_verbose=True, display=None, kwargs={})
2023-09-17 11:23:56,518:INFO:Checking exceptions
2023-09-17 11:24:44,533:INFO:Initializing tune_model()
2023-09-17 11:24:44,533:INFO:tune_model(estimator=XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, gamma=0, gpu_id=-1, grow_policy='depthwise',
              importance_type=None, interaction_constraints='',
              learning_rate=0.300000012, max_bin=256, max_cat_to_onehot=4,
              max_delta_step=0, max_depth=6, max_leaves=0, min_child_weight=1,
              missing=nan, monotone_constraints='()', n_estimators=100,
              n_jobs=-1, num_parallel_tree=1, objective='binary:logistic',
              predictor='auto', random_state=123, reg_alpha=0, ...), fold=None, round=4, n_iter=10, custom_grid=None, optimize=Accuracy, custom_scorer=None, search_library=scikit-learn, search_algorithm=None, early_stopping=False, early_stopping_max_iters=10, choose_better=False, fit_kwargs=None, groups=None, return_tuner=False, verbose=True, tuner_verbose=True, display=None, kwargs={})
2023-09-17 11:24:44,533:INFO:Checking exceptions
2023-09-17 11:24:44,541:INFO:Preparing display monitor
2023-09-17 11:24:44,561:INFO:Copying training dataset
2023-09-17 11:24:44,591:INFO:Checking base model
2023-09-17 11:24:44,592:INFO:Base model : Extreme Gradient Boosting
2023-09-17 11:24:44,604:INFO:Declaring metric variables
2023-09-17 11:24:44,613:INFO:Defining Hyperparameters
2023-09-17 11:24:44,709:INFO:Tuning with n_jobs=-1
2023-09-17 11:24:44,710:INFO:Initializing RandomizedSearchCV
2023-09-17 11:51:56,231:INFO:Initializing tune_model()
2023-09-17 11:51:56,231:INFO:tune_model(estimator=XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, gamma=0, gpu_id=-1, grow_policy='depthwise',
              importance_type=None, interaction_constraints='',
              learning_rate=0.300000012, max_bin=256, max_cat_to_onehot=4,
              max_delta_step=0, max_depth=6, max_leaves=0, min_child_weight=1,
              missing=nan, monotone_constraints='()', n_estimators=100,
              n_jobs=-1, num_parallel_tree=1, objective='binary:logistic',
              predictor='auto', random_state=123, reg_alpha=0, ...), fold=None, round=4, n_iter=10, custom_grid=None, optimize=Accuracy, custom_scorer=None, search_library=scikit-learn, search_algorithm=None, early_stopping=False, early_stopping_max_iters=10, choose_better=False, fit_kwargs=None, groups=None, return_tuner=False, verbose=True, tuner_verbose=True, display=None, kwargs={})
2023-09-17 11:51:56,231:INFO:Checking exceptions
2023-09-17 11:51:56,240:INFO:Preparing display monitor
2023-09-17 11:51:56,261:INFO:Copying training dataset
2023-09-17 11:51:56,316:INFO:Checking base model
2023-09-17 11:51:56,317:INFO:Base model : Extreme Gradient Boosting
2023-09-17 11:51:56,329:INFO:Declaring metric variables
2023-09-17 11:51:56,338:INFO:Defining Hyperparameters
2023-09-17 11:51:56,447:INFO:Tuning with n_jobs=-1
2023-09-17 11:51:56,448:INFO:Initializing RandomizedSearchCV
2023-09-17 11:52:44,457:INFO:Initializing tune_model()
2023-09-17 11:52:44,458:INFO:tune_model(estimator=XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, gamma=0, gpu_id=-1, grow_policy='depthwise',
              importance_type=None, interaction_constraints='',
              learning_rate=0.300000012, max_bin=256, max_cat_to_onehot=4,
              max_delta_step=0, max_depth=6, max_leaves=0, min_child_weight=1,
              missing=nan, monotone_constraints='()', n_estimators=100,
              n_jobs=-1, num_parallel_tree=1, objective='binary:logistic',
              predictor='auto', random_state=123, reg_alpha=0, ...), fold=None, round=4, n_iter=10, custom_grid=None, optimize=Accuracy, custom_scorer=None, search_library=scikit-learn, search_algorithm=None, early_stopping=False, early_stopping_max_iters=10, choose_better=False, fit_kwargs=None, groups=None, return_tuner=False, verbose=True, tuner_verbose=True, display=None, kwargs={})
2023-09-17 11:52:44,458:INFO:Checking exceptions
2023-09-17 11:52:44,466:INFO:Preparing display monitor
2023-09-17 11:52:44,489:INFO:Copying training dataset
2023-09-17 11:52:44,543:INFO:Checking base model
2023-09-17 11:52:44,543:INFO:Base model : Extreme Gradient Boosting
2023-09-17 11:52:44,555:INFO:Declaring metric variables
2023-09-17 11:52:44,564:INFO:Defining Hyperparameters
2023-09-17 11:52:44,669:INFO:Tuning with n_jobs=-1
2023-09-17 11:52:44,669:INFO:Initializing RandomizedSearchCV
2023-09-17 11:53:05,726:INFO:Initializing tune_model()
2023-09-17 11:53:05,726:INFO:tune_model(estimator=XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, gamma=0, gpu_id=-1, grow_policy='depthwise',
              importance_type=None, interaction_constraints='',
              learning_rate=0.300000012, max_bin=256, max_cat_to_onehot=4,
              max_delta_step=0, max_depth=6, max_leaves=0, min_child_weight=1,
              missing=nan, monotone_constraints='()', n_estimators=100,
              n_jobs=-1, num_parallel_tree=1, objective='binary:logistic',
              predictor='auto', random_state=123, reg_alpha=0, ...), fold=None, round=4, n_iter=10, custom_grid=None, optimize=Accuracy, custom_scorer=None, search_library=scikit-learn, search_algorithm=None, early_stopping=False, early_stopping_max_iters=10, choose_better=False, fit_kwargs=None, groups=None, return_tuner=False, verbose=True, tuner_verbose=True, display=None, kwargs={'folds': 5})
2023-09-17 11:53:05,726:INFO:Checking exceptions
2023-09-17 11:53:05,735:INFO:Preparing display monitor
2023-09-17 11:53:05,761:INFO:Copying training dataset
2023-09-17 11:53:05,793:INFO:Checking base model
2023-09-17 11:53:05,794:INFO:Base model : Extreme Gradient Boosting
2023-09-17 11:53:05,805:INFO:Declaring metric variables
2023-09-17 11:53:05,814:INFO:Defining Hyperparameters
2023-09-17 11:53:05,921:INFO:Tuning with n_jobs=-1
2023-09-17 11:53:05,922:INFO:Initializing RandomizedSearchCV
2023-09-17 11:53:11,195:INFO:Initializing tune_model()
2023-09-17 11:53:11,195:INFO:tune_model(estimator=XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, gamma=0, gpu_id=-1, grow_policy='depthwise',
              importance_type=None, interaction_constraints='',
              learning_rate=0.300000012, max_bin=256, max_cat_to_onehot=4,
              max_delta_step=0, max_depth=6, max_leaves=0, min_child_weight=1,
              missing=nan, monotone_constraints='()', n_estimators=100,
              n_jobs=-1, num_parallel_tree=1, objective='binary:logistic',
              predictor='auto', random_state=123, reg_alpha=0, ...), fold=5, round=4, n_iter=10, custom_grid=None, optimize=Accuracy, custom_scorer=None, search_library=scikit-learn, search_algorithm=None, early_stopping=False, early_stopping_max_iters=10, choose_better=False, fit_kwargs=None, groups=None, return_tuner=False, verbose=True, tuner_verbose=True, display=None, kwargs={})
2023-09-17 11:53:11,195:INFO:Checking exceptions
2023-09-17 11:53:11,204:INFO:Preparing display monitor
2023-09-17 11:53:11,225:INFO:Copying training dataset
2023-09-17 11:53:11,278:INFO:Checking base model
2023-09-17 11:53:11,278:INFO:Base model : Extreme Gradient Boosting
2023-09-17 11:53:11,291:INFO:Declaring metric variables
2023-09-17 11:53:11,299:INFO:Defining Hyperparameters
2023-09-17 11:53:11,392:INFO:Tuning with n_jobs=-1
2023-09-17 11:53:11,392:INFO:Initializing RandomizedSearchCV
2023-09-17 11:55:07,801:INFO:Initializing tune_model()
2023-09-17 11:55:07,801:INFO:tune_model(estimator=XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, gamma=0, gpu_id=-1, grow_policy='depthwise',
              importance_type=None, interaction_constraints='',
              learning_rate=0.300000012, max_bin=256, max_cat_to_onehot=4,
              max_delta_step=0, max_depth=6, max_leaves=0, min_child_weight=1,
              missing=nan, monotone_constraints='()', n_estimators=100,
              n_jobs=-1, num_parallel_tree=1, objective='binary:logistic',
              predictor='auto', random_state=123, reg_alpha=0, ...), fold=2, round=4, n_iter=10, custom_grid=None, optimize=Accuracy, custom_scorer=None, search_library=scikit-learn, search_algorithm=None, early_stopping=False, early_stopping_max_iters=10, choose_better=False, fit_kwargs=None, groups=None, return_tuner=False, verbose=True, tuner_verbose=True, display=None, kwargs={})
2023-09-17 11:55:07,801:INFO:Checking exceptions
2023-09-17 11:55:07,810:INFO:Preparing display monitor
2023-09-17 11:55:07,831:INFO:Copying training dataset
2023-09-17 11:55:07,884:INFO:Checking base model
2023-09-17 11:55:07,885:INFO:Base model : Extreme Gradient Boosting
2023-09-17 11:55:07,896:INFO:Declaring metric variables
2023-09-17 11:55:07,905:INFO:Defining Hyperparameters
2023-09-17 11:55:08,015:INFO:Tuning with n_jobs=-1
2023-09-17 11:55:08,015:INFO:Initializing RandomizedSearchCV
2023-09-17 12:06:18,378:INFO:best_params: {'actual_estimator__subsample': 0.5, 'actual_estimator__scale_pos_weight': 2.1, 'actual_estimator__reg_lambda': 5, 'actual_estimator__reg_alpha': 0.05, 'actual_estimator__n_estimators': 300, 'actual_estimator__min_child_weight': 1, 'actual_estimator__max_depth': 10, 'actual_estimator__learning_rate': 0.0005, 'actual_estimator__colsample_bytree': 1}
2023-09-17 12:06:18,380:INFO:Hyperparameter search completed
2023-09-17 12:06:18,380:INFO:SubProcess create_model() called ==================================
2023-09-17 12:06:18,381:INFO:Initializing create_model()
2023-09-17 12:06:18,382:INFO:create_model(estimator=XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, gamma=0, gpu_id=-1, grow_policy='depthwise',
              importance_type=None, interaction_constraints='',
              learning_rate=0.300000012, max_bin=256, max_cat_to_onehot=4,
              max_delta_step=0, max_depth=6, max_leaves=0, min_child_weight=1,
              missing=nan, monotone_constraints='()', n_estimators=100,
              n_jobs=-1, num_parallel_tree=1, objective='binary:logistic',
              predictor='auto', random_state=123, reg_alpha=0, ...), fold=StratifiedKFold(n_splits=2, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=True, verbose=True, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7faf9bfc1910>, kwargs={'subsample': 0.5, 'scale_pos_weight': 2.1, 'reg_lambda': 5, 'reg_alpha': 0.05, 'n_estimators': 300, 'min_child_weight': 1, 'max_depth': 10, 'learning_rate': 0.0005, 'colsample_bytree': 1})
2023-09-17 12:06:18,382:INFO:Checking exceptions
2023-09-17 12:06:18,382:INFO:Importing libraries
2023-09-17 12:06:18,382:INFO:Copying training dataset
2023-09-17 12:06:18,413:INFO:Defining folds
2023-09-17 12:06:18,413:INFO:Declaring metric variables
2023-09-17 12:06:18,423:INFO:Importing untrained model
2023-09-17 12:06:18,423:INFO:Declaring custom model
2023-09-17 12:06:18,433:INFO:Extreme Gradient Boosting Imported succesfully
2023-09-17 12:06:18,451:INFO:Starting cross validation
2023-09-17 12:06:18,453:INFO:Cross validating with StratifiedKFold(n_splits=2, random_state=None, shuffle=False), n_jobs=-1
2023-09-17 12:16:28,293:INFO:Calculating mean and std
2023-09-17 12:16:28,296:INFO:Creating metrics dataframe
2023-09-17 12:16:28,317:INFO:Finalizing model
2023-09-17 12:19:11,433:INFO:Uploading results into container
2023-09-17 12:19:11,433:INFO:Uploading model into container now
2023-09-17 12:19:11,433:INFO:create_model_container: 4
2023-09-17 12:19:11,434:INFO:master_model_container: 4
2023-09-17 12:19:11,434:INFO:display_container: 5
2023-09-17 12:19:11,439:INFO:XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, gamma=0, gpu_id=-1, grow_policy='depthwise',
              importance_type=None, interaction_constraints='',
              learning_rate=0.0005, max_bin=256, max_cat_to_onehot=4,
              max_delta_step=0, max_depth=10, max_leaves=0, min_child_weight=1,
              missing=nan, monotone_constraints='()', n_estimators=300,
              n_jobs=-1, num_parallel_tree=1, objective='binary:logistic',
              predictor='auto', random_state=123, reg_alpha=0.05, ...)
2023-09-17 12:19:11,439:INFO:create_model() succesfully completed......................................
2023-09-17 12:19:11,551:INFO:SubProcess create_model() end ==================================
2023-09-17 12:19:11,564:INFO:create_model_container: 4
2023-09-17 12:19:11,564:INFO:master_model_container: 4
2023-09-17 12:19:11,564:INFO:display_container: 5
2023-09-17 12:19:11,568:INFO:XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, gamma=0, gpu_id=-1, grow_policy='depthwise',
              importance_type=None, interaction_constraints='',
              learning_rate=0.0005, max_bin=256, max_cat_to_onehot=4,
              max_delta_step=0, max_depth=10, max_leaves=0, min_child_weight=1,
              missing=nan, monotone_constraints='()', n_estimators=300,
              n_jobs=-1, num_parallel_tree=1, objective='binary:logistic',
              predictor='auto', random_state=123, reg_alpha=0.05, ...)
2023-09-17 12:19:11,568:INFO:tune_model() succesfully completed......................................
2023-09-17 12:26:48,757:INFO:Initializing plot_model()
2023-09-17 12:26:48,757:INFO:plot_model(plot=feature, fold=None, use_train_data=False, verbose=True, is_in_evaluate=False, display=None, display_format=None, estimator=XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, gamma=0, gpu_id=-1, grow_policy='depthwise',
              importance_type=None, interaction_constraints='',
              learning_rate=0.300000012, max_bin=256, max_cat_to_onehot=4,
              max_delta_step=0, max_depth=6, max_leaves=0, min_child_weight=1,
              missing=nan, monotone_constraints='()', n_estimators=100,
              n_jobs=-1, num_parallel_tree=1, objective='binary:logistic',
              predictor='auto', random_state=123, reg_alpha=0, ...), feature_name=None, fit_kwargs=None, groups=None, label=False, save=False, scale=1, system=True)
2023-09-17 12:26:48,757:INFO:Checking exceptions
2023-09-17 12:26:48,768:INFO:Preparing display monitor
2023-09-17 12:26:48,777:INFO:Preloading libraries
2023-09-17 12:26:48,786:INFO:Copying training dataset
2023-09-17 12:26:48,819:INFO:Copying test dataset
2023-09-17 12:26:48,837:INFO:Plot type: feature
2023-09-17 12:26:48,911:WARNING:No coef_ found. Trying feature_importances_
2023-09-17 12:26:49,194:INFO:Visual Rendered Successfully
2023-09-17 12:26:49,291:INFO:plot_model() succesfully completed......................................
2023-09-17 12:28:21,519:INFO:Initializing plot_model()
2023-09-17 12:28:21,519:INFO:plot_model(plot=confusion_matrix, fold=None, use_train_data=False, verbose=True, is_in_evaluate=False, display=None, display_format=None, estimator=XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, gamma=0, gpu_id=-1, grow_policy='depthwise',
              importance_type=None, interaction_constraints='',
              learning_rate=0.300000012, max_bin=256, max_cat_to_onehot=4,
              max_delta_step=0, max_depth=6, max_leaves=0, min_child_weight=1,
              missing=nan, monotone_constraints='()', n_estimators=100,
              n_jobs=-1, num_parallel_tree=1, objective='binary:logistic',
              predictor='auto', random_state=123, reg_alpha=0, ...), feature_name=None, fit_kwargs=None, groups=None, label=False, save=False, scale=1, system=True)
2023-09-17 12:28:21,519:INFO:Checking exceptions
2023-09-17 12:28:21,530:INFO:Preparing display monitor
2023-09-17 12:28:21,538:INFO:Preloading libraries
2023-09-17 12:28:21,554:INFO:Copying training dataset
2023-09-17 12:28:21,573:INFO:Copying test dataset
2023-09-17 12:28:21,581:INFO:Plot type: confusion_matrix
2023-09-17 12:28:21,604:INFO:Fitting Model
2023-09-17 12:28:21,639:INFO:Scoring test/hold-out set
2023-09-17 12:28:22,590:INFO:Visual Rendered Successfully
2023-09-17 12:28:22,690:INFO:plot_model() succesfully completed......................................
2023-09-17 12:29:03,904:INFO:Initializing plot_model()
2023-09-17 12:29:03,904:INFO:plot_model(plot=lift, fold=None, use_train_data=False, verbose=True, is_in_evaluate=False, display=None, display_format=None, estimator=XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, gamma=0, gpu_id=-1, grow_policy='depthwise',
              importance_type=None, interaction_constraints='',
              learning_rate=0.300000012, max_bin=256, max_cat_to_onehot=4,
              max_delta_step=0, max_depth=6, max_leaves=0, min_child_weight=1,
              missing=nan, monotone_constraints='()', n_estimators=100,
              n_jobs=-1, num_parallel_tree=1, objective='binary:logistic',
              predictor='auto', random_state=123, reg_alpha=0, ...), feature_name=None, fit_kwargs=None, groups=None, label=False, save=False, scale=1, system=True)
2023-09-17 12:29:03,904:INFO:Checking exceptions
2023-09-17 12:29:03,915:INFO:Preparing display monitor
2023-09-17 12:29:03,923:INFO:Preloading libraries
2023-09-17 12:29:03,933:INFO:Copying training dataset
2023-09-17 12:29:03,950:INFO:Copying test dataset
2023-09-17 12:29:03,958:INFO:Plot type: lift
2023-09-17 12:29:03,979:INFO:Generating predictions / predict_proba on X_test
2023-09-17 12:29:04,608:INFO:Visual Rendered Successfully
2023-09-17 12:29:04,703:INFO:plot_model() succesfully completed......................................
2023-09-17 12:29:42,711:INFO:Initializing plot_model()
2023-09-17 12:29:42,711:INFO:plot_model(plot=auc, fold=None, use_train_data=False, verbose=True, is_in_evaluate=False, display=None, display_format=None, estimator=XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, gamma=0, gpu_id=-1, grow_policy='depthwise',
              importance_type=None, interaction_constraints='',
              learning_rate=0.300000012, max_bin=256, max_cat_to_onehot=4,
              max_delta_step=0, max_depth=6, max_leaves=0, min_child_weight=1,
              missing=nan, monotone_constraints='()', n_estimators=100,
              n_jobs=-1, num_parallel_tree=1, objective='binary:logistic',
              predictor='auto', random_state=123, reg_alpha=0, ...), feature_name=None, fit_kwargs=None, groups=None, label=False, save=False, scale=1, system=True)
2023-09-17 12:29:42,712:INFO:Checking exceptions
2023-09-17 12:29:42,723:INFO:Preparing display monitor
2023-09-17 12:29:42,731:INFO:Preloading libraries
2023-09-17 12:29:42,740:INFO:Copying training dataset
2023-09-17 12:29:42,758:INFO:Copying test dataset
2023-09-17 12:29:42,765:INFO:Plot type: auc
2023-09-17 12:29:42,786:INFO:Fitting Model
2023-09-17 12:29:42,844:INFO:Scoring test/hold-out set
2023-09-17 12:29:43,859:INFO:Visual Rendered Successfully
2023-09-17 12:29:43,957:INFO:plot_model() succesfully completed......................................
